language: node_js
notifications:
  email: false
before_script:
- npm ls --production >/dev/null
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: GsNJxjEuaGC3+rPPOHSeUzfllqkfi5pgie1kRsolzFZ0q5F0Q9nkYgSd/Nd1w4XUeB0HgbxCmCsPRbxNVGuBcV1QISwlHXiogBN4nrPwVWYoSgsdijGbpC0Z7z2kS72/R5aNkHIjUkCsihcLG5DjPib9bFEiB5+EnRaGlW6X54Ry8OFCzUehXq7OSp9q14zqvVAzeaOMlsfOvs/2fBR/5vQoDEoIBUpdEgNpwXP092X7LkKJdngvclkgXAqQTw08rtZtjpYs0En8MfSyh2mNzOhSLX3buXqdPr6U+O96G8Zn/JqgqKTmI5S1fSE/rAZl8RQj4m5ZUAWX9TZjc6b+dbEPLi97VqDKtITNd+4O78dHnGH8DpoWONMcZzFgOMI99mPZIodMfHbNH6/sC/KSRvO9k+1MJEFuXhG47sdhBDddsgXi+HXdX3R/bNUGbUCAtGh2KRx1xlf6Q26psNdh0dSyAcLaJ1rDOhDhkIgvCu7HjQEGAVWHLxhGevCYJLsKy2kA5Fx7hcSTr4bnElGebjIyxbaiNDlZSlTnMqWQOF/s2khcy37LXlKQOOxY6hOkkcp24Vb4M3ic+ZEYj1VdnVG/wH7kBVuiZ9dqOSbja1h3t/kd9U9AKCryE28eEGbx5jm7p1wRbgRlsZNip2Yt1Jmtcl5RrsIWSc0Z+1qs1pg=
  - secure: TAVnFZTwN7hw2JM3PpkUE8K7dmHOMioIIuws/kPz2SssqcM19BcTMuNxIfZguhRLuLGO4/zvPXBdp2FpwlijqCycrcGe9Jo3x5C+Rn0hbTlNoHcOoiYahvua1KHXJiV1kP8fYwkeTryPoIM0uGFZYOZeYFeYHvAe7LOEcA1xrxJCDtF5Vi6RNnrKvp3e+hegLfqlua6e/c/zLJDRIIxkdcJZr/akVHJdvStWzAsN0oL7HkAdjN5lwPW2Ko+ZgAcwPHVgKm4fug4eSBilKU5Zp5s70x7iLg+Wim1Dq4CCrkM3w7pwk6OnrBPNOB1c8Gb3JesKC/fcjzC3Psc6KatZhN8cogMDZlBg+cEux2GVOAMJOpwARpT8968ZeqiAOe6BP9pg4cR1iw3qhXzPFFMyz+ssVNWWiai59UuzIZpnY+UcGW7WBh62XR1gNHCGj1OY/3apUJjvcaka5hxdatWIAfNobJbbR3pi5UkhkOLKAB78ovYbgxISGJHCaVaQTqKmE5It7oyaBYtyiycnlqz5EtdWig5SJJmV1qt2oUkJ69jdxr3PzEZQ9SlbegwlCIobvSV+EStJg2fKhSVX2nXvNEVM9SqiNUpYUdQTFdXQpyukPmNJo924l5ZH9qlJBlTpn9Em/qcR1D1V7jT0Yrp+X3NuevtwFT49W/49qjI+Pk0=
